# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically.
# If you change this file, please restart the server process.
#

# Variables accessible via {{ site.myvariable }}.
title: Home
description: >-
  „Kein Ding entsteht planlos, sondern aus Sinn und unter Notwendigkeit.“
domain: leukipp.com
github_username: leukipp

# Build settings.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
include:
 - _pages